### ISSUE TITLE
Maintenance: replaceIDfunc : skip table if no records

### ISSUE THREAD

**Issue by answerquest** [WRI-Cities/static-GTFS-manager#40]
If there are no matching records in a table to replace, then skip that table-key pair and move to next.

Currently it is erroring out if there are no records:
```
[{'table': 'calendar', 'key': 'service_id'}, {'table': 'trips', 'key': 'service_id'}]
WK
ALL
ERROR:tornado.application:Uncaught exception POST /API/replaceID?pw=kmrl&valueFrom=WK&valueTo=ALL (::1)
HTTPServerRequest(...)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "web_wrapper.py", line 1120, in post
    returnMessage = replaceIDfunc(valueFrom,valueTo,tableKeys)
  File "<string>", line 731, in replaceIDfunc
  File "/usr/local/lib/python3.5/dist-packages/tinydb/database.py", line 503, in write_back
    if sorted(doc_ids)[-1] > self._last_id:
IndexError: list index out of range
```

**Comment by answerquest** [comment]
Fixed by putting a count check and skipping loop to next iteration if count is zero.
```
count = len(rows)
if not count:
	continue
```
