### ISSUE TITLE
Fares : If fare_rules has duplicate entries, Pivot function fails

### ISSUE THREAD

**Issue by answerquest** [WRI-Cities/static-GTFS-manager#59]
With the introduction of Fare Rules-Simple tab, it becomes possible for user to inadvertently create duplicating entries. That can cause the python function pivoting the data for Fare Rules -Pivoted tab to error out. Here is the terminal output:

```
ERROR:tornado.application:Uncaught exception GET /API/fareRulesPivoted (::1)
HTTPServerRequest(...)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "web_wrapper.py", line 209, in get
    fareRulesPivotedArray = df.pivot(index='origin_id', columns='destination_id', values='fare_id').reset_index().rename(columns={'origin_id':'zone_id'}).to_dict(orient='records', into=OrderedDict)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 4382, in pivot
    return pivot(self, index=index, columns=columns, values=values)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/reshape/reshape.py", line 389, in pivot
    return indexed.unstack(columns)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/series.py", line 2224, in unstack
    return unstack(self, level, fill_value)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/reshape/reshape.py", line 474, in unstack
    fill_value=fill_value)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/reshape/reshape.py", line 116, in __init__
    self._make_selectors()
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/reshape/reshape.py", line 154, in _make_selectors
    raise ValueError('Index contains duplicate entries, '
```

**Comment by answerquest** [comment]
Duplicate entries should be prevented at storing stage, but to prepare for any eventuality (like if a fresh feed carrying duplicate fare rules has been imported), the pivoting function can be preceded by a `.drop_duplicates` function of pandas itself.  
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop_duplicates.html

```
if len(fareRulesArray):
	df = pd.DataFrame(fareRulesArray).drop_duplicates(keep='first', inplace=True)
	# skipping duplicate entries if any, as pivoting errors out if there are duplicates.
	fareRulesPivotedArray = df.pivot(index='origin_id', columns='destination_id', values='fare_id').reset_index().rename(columns={'origin_id':'zone_id'}).to_dict(orient='records', into=OrderedDict)
```
Solved for this case. Code to be updated. Ought to apply the `.drop_duplicates` function at all DB saving stages, and it can happen gracefully.
