### ISSUE TITLE
Linux binary: running without terminal and closing browser prevents program from running again

### ISSUE THREAD

**Issue by answerquest** [WRI-Cities/static-GTFS-manager#71]
This is in an Ubuntu OS, and concerns Linux executable that is under development and hasn't been released yet as of release v1.4.2.
 
Steps:  
1.  Double-click on the GTFSManager executable to launch the program.
2. Prompt asks whether you want to execute or execute in terminal.
![linux binary execute prompt](https://user-images.githubusercontent.com/9089552/39402727-616dddd4-4b85-11e8-975f-9647f92e4dba.png)
3. We pick the default option ie Execute.
4. In this mode, the terminal and the messages there never show up. Directly a browser tab opens with the program's home page.
5. After some use, we close the browser tab to close the program.
6. We double-click the program again to run it another time. After some waiting, we realise that nothing has happened.
7. We double-click the program again and choose to execute in Terminal. An empty terminal opens but nothing happens there.. it's stuck.
8. We run the program from another terminal opened at the folder instead of double-clicking:  
```
$ ./GTFSManager
static GTFS Manager
Fork it on Github: https://github.com/WRI-Cities/static-GTFS-manager/
Starting up the program, loading dependencies, please wait...


Loaded dependencies, starting static GTFS Manager program.
Traceback (most recent call last):
  File "GTFSManager.py", line 1258, in <module>
    app.listen(port)
  File "site-packages/tornado/web.py", line 1986, in listen
  File "site-packages/tornado/tcpserver.py", line 144, in listen
  File "site-packages/tornado/netutil.py", line 163, in bind_sockets
OSError: [Errno 98] Address already in use
[9559] Failed to execute script GTFSManager
```
9. So unless we reboot the system, the program has effectively crashed.

**Comment by answerquest** [comment]
### Analysis
- At first run, the program wasn't actually terminated when the browser tab was closed. Because the browser doesn't control the program. So this whole time the program is still running in the background.
- This is confirmed by visiting the URL `http://localhost:5000/` again in the browser (note: port number at end may vary on different systems). The program is up and working.

### Quickfix
To really terminate the program, ref: [How to know what program is listening on a given port?](https://askubuntu.com/questions/278448/how-to-know-what-program-is-listening-on-a-given-port)  
```
$ lsof -i :5000
COMMAND    PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
GTFSManag 7757 nikhil    3u  IPv6  96051      0t0  TCP *:5000 (LISTEN)
GTFSManag 7757 nikhil    4u  IPv4  96052      0t0  TCP *:5000 (LISTEN)

$ kill 7757
<no response but program is terminated, confirmed by being able to run it again>
```

### Longfix
The binary should force 'Execute in Terminal' option. Don't allow terminal-less execution. Or, spawn the terminal upon execution.
